language: python
env:
  - DJANGO_SETTINGS_MODULE='usaidmmc.testsettings' DATABASE_URL='postgres://postgres:@/test_usaidmmc'
python:
  - "2.6"
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install coveralls
before_script:
  - psql -c 'create database test_usaidmmc;' -U postgres
script:
  - flake8 usaidmmc
  - ./manage.py test --with-coverage --cover-package=usaidmmc
after_success:
  - coveralls
